# Generated by Django 2.1.3 on 2019-02-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aqms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('voltage', models.DecimalField(decimal_places=3, max_digits=5)),
                ('ampere', models.DecimalField(decimal_places=3, max_digits=5)),
                ('watts', models.DecimalField(decimal_places=3, max_digits=5)),
                ('windspeed', models.SmallIntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
