# Generated by Django 2.1.3 on 2019-03-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aqms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppm', models.DecimalField(blank=True, decimal_places=3, max_digits=6)),
                ('vol_pz', models.DecimalField(decimal_places=3, max_digits=6)),
                ('amp_pz', models.DecimalField(decimal_places=3, max_digits=6)),
                ('wat_pz', models.DecimalField(decimal_places=3, max_digits=6)),
                ('vol_wt', models.DecimalField(decimal_places=3, max_digits=6)),
                ('amp_wt', models.DecimalField(decimal_places=3, max_digits=6)),
                ('wat_wt', models.DecimalField(decimal_places=3, max_digits=6)),
                ('windspeed', models.SmallIntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
