# Generated by Django 2.1.3 on 2019-02-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aqms',
            name='ppm',
        ),
    ]
