# Generated by Django 2.1.3 on 2019-03-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqms',
            name='ppm',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
