# Generated by Django 2.1.3 on 2019-03-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqms', '0003_auto_20190220_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqms',
            name='voltage',
            field=models.FloatField(),
        ),
    ]
