# Generated by Django 2.1.3 on 2019-03-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqms', '0004_auto_20190305_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqms',
            name='ppm',
            field=models.FloatField(),
        ),
    ]
