# Generated by Django 2.1.3 on 2019-03-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqms', '0005_auto_20190305_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqms',
            name='ampere',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='aqms',
            name='watts',
            field=models.FloatField(),
        ),
    ]
