# Generated by Django 2.1.3 on 2019-03-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqms', '0006_auto_20190305_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aqms',
            old_name='ampere',
            new_name='amp_pz',
        ),
        migrations.RenameField(
            model_name='aqms',
            old_name='voltage',
            new_name='amp_wt',
        ),
        migrations.RenameField(
            model_name='aqms',
            old_name='watts',
            new_name='vol_pz',
        ),
        migrations.AddField(
            model_name='aqms',
            name='vol_wt',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aqms',
            name='wat_pz',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aqms',
            name='wat_wt',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
    ]
