# Generated by Django 2.1.3 on 2019-03-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqms', '0007_auto_20190306_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqms',
            name='amp_pz',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='aqms',
            name='amp_wt',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='aqms',
            name='ppm',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='aqms',
            name='vol_pz',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='aqms',
            name='vol_wt',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='aqms',
            name='wat_pz',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='aqms',
            name='wat_wt',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
