# Generated by Django 2.1.3 on 2019-03-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqms', '0008_auto_20190307_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqms',
            name='amp_pz',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='aqms',
            name='vol_pz',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='aqms',
            name='wat_pz',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
