# Generated by Django 2.1.3 on 2019-01-07 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('colevel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colevel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='colevel',
            name='time',
        ),
        migrations.AddField(
            model_name='colevel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
