# Generated by Django 2.1.3 on 2019-01-07 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('colevel', '0002_auto_20190107_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colevel',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='colevel',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colevel',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
